### ISSUE TITLE
Nix not finding some shared libraries (Linux)

### ISSUE THREAD

**Issue by scttnlsn** [jamii/bluetron#5]
Hey all!  Thanks so much for the invite to this.  Looking forward to chatting later this week!  I was able to get things running but had to comment out a few `buildInputs` in the Nix config.

With `ozone_linux` present I get the following error:

```
searching for dependencies of /nix/store/pjnim9xxvvsg45wc9h0n3560i1lvc4g7-ozone/Ozone
  libjlinkarm.so.6 -> not found!
  libQtGui.so.4 -> found: /nix/store/cslh020h627azip76kalvqdgwpc1ajz8-qt-4.8.7/lib/libQtGui.so.4
  libQtCore.so.4 -> found: /nix/store/cslh020h627azip76kalvqdgwpc1ajz8-qt-4.8.7/lib/libQtCore.so.4
builder for '/nix/store/47sak860ldfx7r60bf4cfkjz0qqghzsz-ozone.drv' failed with exit code 1
error: build of '/nix/store/47sak860ldfx7r60bf4cfkjz0qqghzsz-ozone.drv', '/nix/store/4x7l8p6ai0xwv2z1iz757v6vs37r0gvc-jlink-V686f.drv' failed
```

I tried uncommenting the `jlink` input but got the same error.  Do I need `libjlinkarm.so.6` available outside of Nix or should that lib be present in the Nix environment?

Was also having issues with `nrf_command_line_tools_linux`.  It installs to the Nix env just fine but then when I try to run `nrfjprog` I get:

```
ERROR: nrfjprog DLL load failed. Try again. If it keps failing, please
ERROR: reinstall nrfjprog.
```

(lol, keps)

Since I already had `nrfjprog` installed via Debian package I was able to comment out `nrf_command_line_tools_linux` in the Nix config and use my system's version.

I'm not at all familiar with Nix but it seems like perhaps there's an issue loading some shared libraries.  Would certainly appreciate any advice you have related to this but it's also not a big deal since I can work around this quite easily in this case.

Thanks!

**Comment by jamii** [comment]
I haven't gotten either to actually run under nix yet. Didn't mean to check in a broken shell though, sorry. I commented them out for now.

Both are easy to install from the nordic site, I'm just trying to package them for myself because I'm on nixos and can't use their .debs.
